Repository l3mpire/lemverse, pull requests merged in 2022-11, with the labels that each got.

#193 Update Meteor version to 2.8
  app/.meteor/packages
  app/.meteor/release
  app/.meteor/versions
Labels: enhancement

#199 Allow custom interactions on entities
  core/client/entity-manager.js
  core/client/helpers.js
  core/client/ui/toolboxes/entity-editor.hbs.html
  core/client/ui/toolboxes/entity-editor.js
  core/client/ui/toolboxes/entity-editor.scss
  core/client/user-manager.js
Labels: enhancement

#198 Extract logic to open URLs from zones
  core/client/entity-manager.js
  core/client/helpers.js
  core/client/lemverse.js
  core/client/scenes/scene-world.js
  core/client/ui/toolboxes/entity-editor.hbs.html
  core/client/ui/toolboxes/entity-editor.js
  core/client/ui/toolboxes/entity-editor.scss
  core/client/url-opener.js
  core/client/user-manager.js
  core/client/zone-manager.js
Labels: enhancement

#163 Report users
  core/client/ui/user-profile.hbs.html
  core/client/ui/user-profile.js
  core/modules/messages/client/messages-list.hbs.html
  core/modules/messages/client/messages-list.js
  core/modules/messages/client/messages-list.scss
  core/modules/notifications/client/notifications.hbs.html
  core/modules/notifications/client/notifications.scss
  core/modules/report/client/report.hbs.html
  core/modules/report/client/report.js
  core/modules/report/client/report.scss
Labels: enhancement

#201 Entities: show all non-pickable entities in the target list
  core/client/ui/toolboxes/entity-editor.js
Labels: enhancement

#202 Preserves the notification even if the user is in discussion with the sender
  core/client/lemverse.js
Labels: enhancement

#200 Add JWT user login
  README.md
  core/client/passwordless.js
  core/server/accounts.js
Labels: enhancement

#206 Fix broken tilesets
  core/client/ui/editor-tilesets.js
  core/client/ui/toolboxes/tileset-toolbox.js
Labels: bug

#205 Use level spawn position when switching level
  core/client/ui/levels.js
  core/server/levels.js
Labels: bug

#203 Messages: split console state from the message module
  core/modules/console/client/console.hbs.html
  core/modules/console/client/console.js
  core/modules/console/client/console.scss
  core/modules/messages/client/helpers.js
  core/modules/messages/client/messages-list.hbs.html
  core/modules/messages/client/messages-list.js
  core/modules/messages/client/messages-list.scss
  core/modules/textual-communication-tools/client/textual-communication-tools.scss
Labels: enhancement

#211 Meet: export computeRoomToken and computeRoomName
  core/modules/meet/server/meet.js
Labels: enhancement

#210 Enhance peer
  app/settings-dev.json
  core/client/helpers.js
  core/client/network-manager.js
  core/client/peer.js
  core/client/user-manager.js
  core/client/user-voice-recorder-ability.js
  core/modules/punch-ability/client/punch-ability.js
Labels: bug, enhancement

#215 Fix guest css
  core/client/lemverse.scss
  core/client/ui/user-panel.hbs.html
  core/client/ui/user-panel.js
  core/client/ui/user-panel.scss
  core/client/user-manager.js
Labels: bug

#217 Messages: add method to retrieve the targeted channel ID
  core/modules/messages/client/messages.js
Labels: enhancement

#218 Add map on entity depth
  core/client/ui/toolboxes/entity-editor.hbs.html
  core/client/ui/toolboxes/entity-editor.js
Labels: enhancement

#214 Add new resizable template for meet.js
  core/client/lemverse.hbs.html
  core/client/lemverse.scss
  core/client/ui/components/resizable/resizable.hbs.html
  core/client/ui/components/resizable/resizable.js
  core/client/ui/components/resizable/resizable.scss
  core/client/url-opener.js
  core/modules/meet/client/meet.js
Labels: enhancement

#212 Guilds: avoid returning all fields to the client
  core/server/guilds.js
  core/server/users.js
Labels: bug
